#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

paths=( "submodules/soomla-ios-core")
build=../build/ios

rm -rf $build
mkdir -p $build

for path in "${paths[@]}"
do
  cd $path
  ./build_all
  cd -
  cp -R $path/build/* $build/
done


path="soomla-native/projects/cocos2dx-ios-core"

cd $path
./build_all_jsb
cd -
cp -R $path/build/* $build/

cd - > /dev/null
