#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

paths=( "submodules/soomla-ios-core")
build=../build/ios

rm -rf $build
mkdir -p $build

for path in "${paths[@]}"
do
  $path/build_all
  cp -R $path/build/* $build/
done


path="soomla-native/projects/cocos2dx-ios-core"

$path/build_all_jsb
cp -R $path/build/* $build/

cd - > /dev/null
