#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

paths=( "submodules/soomla-ios-core" "soomla-native/projects/cocos2dx-ios-core" )
build=../build/ios

rm -rf $build
mkdir -p $build

for path in "${paths[@]}"
do
  $path/build_all
  cp -R $path/build/* $build/
done

cd - > /dev/null
